csm-health-checks/barebones-boot/barebonesImageTest.py
The option for the user to supply a compute node to use for the image boot test was not working.  This change takes the input argument and makes it flow into the rest of the script so it will be used.
* Resolves CASMTRIAGE-2732
* Wasp
I loaded the modified script on wasp and disabled that portion of the script that actually initiates the boot, but kept the argument processing and finding a compute node to use for the test.  I verified that when a node is specified on the command line it now flows through to the function that looks for an available node.  I also tested scenarios where there is nothing passed in and where an incorrect node xname is used.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? …
=> CASMTRIAGE-2732 - Fix barebones image boot test script to get input target compute node.

cmsdev/internal/lib/k8s/k8s.go, cmsdev/internal/test/ims/signingkeys.go, cray-cmstools-crayctldeploy.spec
TLDR; This fixes two testcase bugs in the new IMS signing keys test. Without these fixes, this test always fails, which is bad since this test is part of the standard CSM health check procedure performed during installs.
In csm-1.2 a new subtest was added to the cmsdev tool to test IMS signing keys. When the test was added, no system was available with the new feature, so the test could not be successfully run before it was merged. As it turns out, the test had two bugs in it. This PR addresses those. Specifically:
* The test used the kubectl command to get information from a Kubernetes configmap. Something in the way it was doing that was causing issues with YAML parsing. I verified that the information in Kubernetes was correct, which led me to conclude that this was some golang …
=> CASMCMS-7691: Fix testcase bugs in new IMS signing keys test

csm-health-checks/barebones-boot/barebonesImageTest.py
This PR just corrects some typos in the messages and comments of the barebones boot test.
* https://github.com/Cray-HPE/docs-csm/pull/690 This PR corrects one of the typos that was copied into the install docs.
None beyond verifying that it builds, since only messages and comments were changed.
Very low risk.
- [N/A] Version number(s) incremented, if applicable
- [N/A] Copyrights updated
- [N/A] CHANGELOG.md updated
- [N/A] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
=> CASMINST-3725: Fix typos in barebones boot test

csm-health-checks/barebones-boot/barebonesImageTest.py
Replace the sole remaining HSM v1 API call with v2. I confirmed that for this endpoint, with the parameters we are using, there is no change in behavior, so just swapping the endpoint is all that is needed.
=> CASMCMS-8073: Use HSMv2 API instead of v1

CHANGELOG.md, csm-health-checks/barebones-boot/barebonesImageTest.py
In some cases a person running the barebones boot test has a specific node that is available to be rebooted. The current behavior of the test (to choose a different node if the requested node is unavailable) is not ideal, because it means that people in that situation are taking a risk by executing the test. Even if they are sure that their node is available, if there is an HSM problem or they make a typo, a different compute node would be rebooted.
This PR changes the behavior of the test so that if the user specifies a compute node, the test will fail if that node is not found.
As before, the test default behavior (if no node is specified) is to pick one itself, so that ability still exists. This just gives users a safe way to run the test without risking different compute nodes being …
=> CASMCMS-8069: Barebones boot test now fails if user requested compute node is not available

CHANGELOG.md, Jenkinsfile.github, Makefile, cray-cmstools-crayctldeploy.spec, update_versions.conf
When I enabled git versioning for the repo I forgot to have it set the RPM release field, like what we had to do with BOS. This PR corrects that.
=> Set RPM version and release fields

CHANGELOG.md, csm-health-checks/barebones-boot/barebonesImageTest.py
Currently the barebones boot test selects the first IMS image it finds with "barebones" in the name. In some cases, there may be multiple such images, and in other cases, an administrator may have removed or renamed the provided CSM barebones image. This PR adds an argument to the test allowing the user to specify the ID of an IMS image to be used, if desired.
I tested this on rocket, both with and without an ID being specified, to make sure that both cases still work correctly. I also tested to make sure it behaved appropriately if an invalid ID is specified.
Low risk.
=> CASMCMS-8068: Allow user to specify ID of IMS image used for barebones boot test

CHANGELOG.md, cmsdev/internal/test/bos/bos.go
The cmsdev test tool currently tests BOS CLI commands both with and without explicitly specifying the version. However, the tool has not yet been updated to know about BOS v2, and the CLI now defaults to BOS v2 when no version is explicitly specified. The syntax of the BOS v2 CLI commands is not identical to BOS v1, so this causes the test to fail when it tries to run CLI commands without a version explicitly specified.
This PR just removes the function calls that were testing the BOS CLI without explicitly specifying the version. This means it will only make BOS CLI calls by explicitly specifying BOS v1, thus avoiding the problem.
- Resolves [CASMINST-5240](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5240)
- The "correct" fix for this is to update cmsdev so it can also test …
=> Release 1.6.1: CASMINST-5240: cmsdev: Disable BOS CLI testing without explicitly specifying BOS version

CHANGELOG.md, cmsdev/internal/lib/common/helpers.go, cmsdev/internal/lib/test/cli.go, cmsdev/internal/test/bos/bos.go, cmsdev/internal/test/bos/bos_api.go, cmsdev/internal/test/bos/bos_cli.go, cmsdev/internal/test/bos/bos_components.go, cmsdev/internal/test/bos/bos_healthz.go, cmsdev/internal/test/bos/bos_options.go, cmsdev/internal/test/bos/bos_session.go, cmsdev/internal/test/bos/bos_sessiontemplate.go, cmsdev/internal/test/bos/bos_version.go
The primary purpose of this PR was to add BOS v2 test coverage to the cmsdev test tool. While doing that, I did a minor overhaul of the cmsdev BOS CLI and API testing. It had a lot of cruft and I didn't like the idea of having the new API/CLI tests totally different from the old ones, but I also didn't like the idea of making the new ones have to match the old ones. So I just re-wrote all of them.
These are fairly basic tests. Mostly they just hit the read-only endpoints and make sure that they get back something vaguely reasonable. For the most part that just means validating the status code and the high-level data object returned (dictionary, list, etc). In a few cases, it checks specific fields in the returned data (for example, when doing a GET for a specific session template, it …
=> CASMCMS-8087: Add BOSv2 support to cmsdev test tool

CHANGELOG.md, cmsdev/internal/test/bos/bos_components.go, cmsdev/internal/test/bos/bos_healthz.go, cmsdev/internal/test/bos/bos_options.go, cmsdev/internal/test/bos/bos_session.go, cmsdev/internal/test/bos/bos_sessiontemplate.go, cmsdev/internal/test/bos/bos_version.go
This modifies the cmsdev BOS tests as follows:
- For the things exclusive to BOS v2 (options, components), remove the corresponding CLI tests where the BOS version is not specified (with v1 as the default, they won't work without the version specified)
- For the things which exist in both BOS versions, update the BOS tests so that when calling the CLI without the version, it uses the correct v1 command format (session vs sessions, sessiontemplate vs sessiontemplates) and, in the cases where they differ (just sessions), calls the appropriate version of the test function.
- Resolves [CASMCMS-8193](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8193)
- Related to the corresponding CLI change implemented with [CASMCMS-8192](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8192)
- …
=> CASMCMS-8193: cmsdev: Default CLI BOS version back to v1

CHANGELOG.md, cmsdev/internal/test/vcs/vcs_repo.go
While looking into a Gitea problem on starlord I stumbled across a case where the cmsdev VCS test tries to dereference a null pointer and has an ugly crash. This is in the error path of the test, and isn't the cause of the test failure. But it does cause the cmsdev suite to crash instead of running the rest of its tests. 
After I identified the problem, I spotted one other place where it existed in the code. This PR corrects both. The fix is very simple -- delete the two lines of code which are using the null pointer. They were accidentally cut and pasted from other locations and were never meant to be there.
This resolves [CASMCMS-8203](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8203).
This was found during debug of [CASMTRIAGE-4074](https://jira-pro.its.hpecorp.net:8443/browse/ …
=> CASMCMS-8203: cmsdev: Do not dereference null points in VCS test error paths

CHANGELOG.md, cmsdev/internal/test/bos/bos_version.go
I noticed that there were 3 BOS CLI commands not being covered by cmsdev. This PR adds very basic tests of them (just making sure they return dictionary objects). The added commands are:
- `cray bos list`
- `cray bos v1 list`
- `cray bos v2 list`
I ran the updated test on surtur and verified that all 3 new tests were executed successfully.
Relevant excerpt:
```text
...
Testing BOS CLI (v1 list)
Testing BOS CLI (v1 version list)
Testing BOS CLI (v2 list)
Testing BOS CLI (v2 version list)
Testing BOS CLI (version list)
Testing BOS CLI (list)
Testing BOS CLI (v1 healthz list)
...
```
Low risk. The new tests are very basic, and re-use existing generic CLI test functions (since we are just making sure that we get a dictionary back). Because of this, the chance of introducing a new test error …
=> CASMCMS-8210: cmsdev: Add CLI tests for bos list, bos v1 list, and bos v2 list

CHANGELOG.md, cmsdev/internal/lib/common/helpers.go, cmsdev/internal/test/ipxe_tftp/ipxe_tftp.go
The cmsdev tftp file transfer subtest fails when run from master NCNs, now that the modprobe pods do not run on master nodes. I discussed this with Jeanne. This is not a problem beyond the fact that the test fails. This PR modifies cmsdev so that that particular subtest will not run when cmsdev is run on master NCNs.
- Resolves [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
- Problem created by the change made in [CASMCMS-8450](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8450)
- Problem reported by [CASMTRIAGE-5071](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5071)
I will have an additional PR to add a Goss test which runs the cmsdev tftp test on a worker NCN, so we do not lose this test coverage. I will also update the CSM health check docs …
=> CASMCMS-8473: Do not run tftp file transfer test from master NCNs

CHANGELOG.md, cmsdev/internal/lib/cms/cms.go
As part of adding the cmsdev test tool to Goss, Mikhail noticed that if he ran it before CSM was deployed, it hit a null pointer exception. While the tool is not intended to be useful before CSM is deployed, it still doesn't need to be failing in such an ugly way. The cause is actually a fairly basic logic problem where a data structure wasn't initialized (because the services aren't running), but then later it tries to update a field in that data structure.
There are actually a few instances of this in the same function.
This PR rearranges things so that any attempt to write to the data structure happens in a context when it is initialized (mostly this just involved moving some of the code inside of an earlier conditional).
I don't have a system handy where I can reproduce the original …
=> CASMCMS-8479: cmsdev: Fix null pointer exception when run before CSM is deployed

CHANGELOG.md, cmsdev/internal/cmd/test.go
@mtupitsyn  requested a way to have cmsdev list all of the possible tests it can run. Currently it does provide that information in usage messages, but there isn't a proper way to just query it for the information. This ticket adds a "--list" or "-l" argument that can be used with "cmsdev test". It will print a list of all valid tests that cmsdev can run (on a single line, separated by whitespace).
The "--exclude-aliases" option is also added, which doesn't include aliases in this output. For example, it would omit "all" (which is an alias to run all of the tests) and "gitea" (which is an alias for the "vcs" test).
These changes are all made to the section of cmsdev which does argument parsing, before any tests are run. It should have no impact on the normal usage of the tool to run …
=> CASMCMS-8480: cmsdev: Add option to list possible tests to run

CHANGELOG.md, cmsdev/internal/lib/test/test.go
I noticed in a recent ticket the following message in a cmsdev test log:
```text
ERROR (run tag 04xIh-conman): Expected at least 2 pod pods but found 1: cray-console-node-0
```
This probably was meant to say `2 cray-console-node pods` not `2 pod pods`.
This PR fixes that. In addition, I noticed some of the Kubernetes check messages don't include the namespace, but probably should. So this PR changes that as well.
Finally, I found a couple of cases where string formatting was being used unnecessarily (%s with a literal string parameter), so I simplified those.
No test behavior is changed, just the messages.
- I discovered the typo while debugging [CASMTRIAGE-5139](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5139).
- Resolves …
=> CASMCMS-8498: cmsdev: Fix typo in message; add namespace info to some messages

CHANGELOG.md, cmsdev/internal/lib/k8s/k8s.go
Currently the `cmsdev` test logs (and output, if run in verbose mode) contain a LOT of duplicate lines about the contents of the `KUBECONFIG` environment variable. This is because the `cmsdev` Kubernetes code initializes the Kubernetes configuration every time the Kubernetes API is used, and this in turn looks up the value of that environment variable. However, the K8s configuration really only needs to be initialized once per `cmsdev` execution. This PR makes that change, which will prevent with duplicate output/log messages, and also presumably will offer a (very small) performance benefit.
- Resolves [CASMCMS-8496](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8496)
I tested on wasp and verified that the duplicate output is no longer created, and that all tests continue to work …
=> CASMCMS-8496: cmsdev: Stop redundant output/logging of KUBECONFIG env var

CHANGELOG.md, cmsdev/internal/test/vcs/vcs.go
Starting in CSM 1.5, the VCS database backup job will have a different name, with the switch over to logical DB backups. This PR informs the cmsdev test tool of this change, so that it won't panic at the absence of the backup job.
- Resolves [CASMCMS-8513](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8513)
- [CASMCMS-8457](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8457) originally made the change to VCS to enable the new style of backups. Ideally that Jira should also have updated the test, or opened a new ticket to do it.
- Bug discovered by [CASMTRIAGE-5130](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5130)
- VCS itself currently has a bug preventing it from doing its new logical DB backups. That is being addressed with …
=> CASMCMS-8513: cmsdev: Update VCS test to reflect change to logical DB backups

CHANGELOG.md, cmsdev/internal/test/bos/bos.go
On CSM 1.5, the cmsdev BOS test fails, because of the change to Bitnami for etcd. This resulted in some pod and PVC name changes. This PR modifies the BOS test to account for these changes.
Also, in doing this I noticed that the BOS test was not hitting other errors more by happenstance than anything else. Some of the things it was trying to check were not actually true, but it was not checking them very carefully. This PR simplifies the Kubernetes pod checks for BOS, mainly just making sure that the etcd pods look good, and that all pods are either Running or (for some transient pods) Succeeded.
- Resolves [CASMCMS-8514](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8514)
- Bug discovered by [CASMTRIAGE-5129](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5129)
I tested …
=> CASMCMS-8514: cmsdev: Modify BOS test to handle change to Bitnami for etcd; make pod checks more flexible

CHANGELOG.md, cmsdev/README.md, cmsdev/internal/cmd/test.go, cmsdev/internal/lib/common/common.go, cmsdev/internal/lib/common/printlog.go, cmsdev/internal/test/bos/bos.go, cmsdev/internal/test/cfs/cfs.go, cmsdev/internal/test/conman/conman.go, cmsdev/internal/test/ims/ims.go, cmsdev/internal/test/ipxe_tftp/ipxe_tftp.go, cmsdev/internal/test/vcs/vcs.go
This is to make it easier to debug some of the failures seen on automated test runs when the test environment is not available for live debug.
No change to the tests themselves, just to the logic around the Kubernetes debug data collection.
Tested on wasp to make sure it works as expected in the normal case, as well as if an alternate Kubernetes artifact directory is specified, or if no logging is specified, or both.
Low risk.
=> CASMCMS-8529: cmsdev: Collect Kubernetes information by default on failures

CHANGELOG.md, cmsdev/internal/lib/common/helpers.go, cmsdev/internal/lib/k8s/k8s.go, cmsdev/internal/test/ims/signingkeys.go, cmsdev/internal/test/ipxe_tftp/ipxe_tftp.go, cmsdev/internal/test/ipxe_tftp/tftp_get.go
The cmsdev ipxe test includes validating that the iPXE image is being generated and that it can be downloaded over tftp. However, the test currently only does this for the regular iPXE binary, not the debug binary. It also has the name of the binary hard-coded to be the default value, AND it assumes that the binary is being built. However, the cray-ipxe-settings configmap can be modified so that the name of the binary is not the default, or so that it is not being built at all. Currently the test will fail in such situations.
This PR makes the following improvements to this test:
1) The test now covers both the regular binary and the debug binary
2) The test uses the ConfigMap to determine the names of the binaries
3) The test uses the ConfigMap to determine whether or not the binaries …
=> CASMCMS-8602: cmsdev: Update iPXE/TFTP test to use cray-ipxe-settings configmap

CHANGELOG.md, cmsdev/internal/lib/common/common.go
bzip2 is not available on all systems. gzip is more universally available, so this changes cmsdev to use it when compressing test artifacts in the case of failure.
* Resolves [CASMTRIAGE-5598](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5598)
* [Backport to master](https://github.com/Cray-HPE/cms-tools/pull/112)
I tested this on drax. I redeployed the tftp pod and ran the test before it was done restarting. This caused the test to fail, as expected. I verified that it correctly compressed the artifacts using gzip.
Very low risk.
=> CASMTRIAGE-5598: cmsdev: Compress artifacts using gzip instead of bzip2

CHANGELOG.md, cmsdev/internal/test/ipxe_tftp/ipxe_tftp.go, cmsdev/internal/test/ipxe_tftp/tftp_get.go
This PR updates the iPXE/TFTP test so that it tests transferring Arm binaries as well as x86 binaries. It covers both debug and regular, and looks at the configmap to determine which ones are being built (and thus should be tested).
* Resolves [CASMCMS-8504](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8504)
* Resolves [CASMTRIAGE-5597](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5597)
I tested the updated version on ashton (installed with 1.5.0-alpha.66) and verified that it worked as expected.
Without this test change, the ipxe/tftp test will always fail on CSM 1.5.
=> CASMCMS-8504: cmsdev: Added support for ARM binaries to iPXE/TFTP test

CHANGELOG.md, cmsdev/internal/lib/common/common.go, cmsdev/internal/lib/common/rand.go, cmsdev/internal/lib/k8s/k8s.go, cmsdev/internal/lib/test/api.go, cmsdev/internal/test/bos/bos.go, cmsdev/internal/test/bos/bos_api.go, cmsdev/internal/test/bos/bos_cli.go, cmsdev/internal/test/bos/bos_components.go, cmsdev/internal/test/bos/bos_healthz.go, cmsdev/internal/test/bos/bos_session.go, cmsdev/internal/test/bos/bos_session_tests.go, cmsdev/internal/test/bos/bos_sessiontemplate.go, cmsdev/internal/test/bos/bos_sessiontemplate_tests.go, cmsdev/internal/test/bos/bos_version.go
This adds good path multitenancy GET API tests for supported BOS v2 endpoints. For version and health endpoints, it just tries the same queries with a tenant specified.
For sessions, and session templates, first it lists all items, with no tenant specified. If any items are listed that belong to a tenant, then it also tests listing all items that belong to that tenant, as well as doing a GET for a specific item owned by that tenant (found from the original listing). 
If no items owned by tenants are found, it still attempts to list all items belonging to a random (possibly nonexistent) tenant, and just verifies that the response is an empty list, as expected.
For components, it also starts by making an untenanted query to list all components, and does a GET request on the first item in …
=> CASMCMS-8553: Add good path multitenancy testing for BOS API

CHANGELOG.md, cmsdev/internal/cmd/test.go
While debugging [CASMTRIAGE-6371](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6371), it became apparent that it would be very nice if the cmsdev test tool had an option that stopped it from deleting the temporary test files it creates during execution.
This PR adds that option. It is a very small change -- adding the new command line option, and then using it to determine whether or not to set a deferred call to the function that deletes the temporary directory.
* Inspired by debug of [CASMTRIAGE-6371](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6371)
* Resolves [CASMCMS-8872](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8872)
I tested this on starlord (running CSM 1.5.0-beta.79), running tests both with and without the new option specified. In both cases, it behaved as …
=> CASMCMS-8872: cmsdev: Add --no-cleanup option to make debug easier

CHANGELOG.md, cms-tftp/cray-tftp-upload
(cherry picked from commit 85567454e110924d4988c7dc2a17470e3a4c04ec)
(cherry picked from commit bf705bf451d136ca050700c17c00c1e35da685be)
(cherry picked from commit 50d5e08ecaf4a1cf298e5f78a1a01eede83c3f88)
(cherry picked from commit 4a7e646bde314afe0f6796ffcaff3c24505e701b)
=> CASMTRIAGE-6578: Updated cray-tftp-upload script to handle more than one ipxe pod (CSM1.5)

CHANGELOG.md, cmsdev/internal/test/bos/bos.go
Remove the remaining test checks that are specific to BOS v1 and that will fail once it is removed.
=> CASMCMS-7329: cmsdev: Remove BOS-v1-specific checks

.gitignore, CHANGELOG.md, cmsdev/internal/test/cfs/cfs.go, cmsdev/internal/test/cfs/cfs_api.go
The cmsdev CFS test was failing in cases where calls to CFS v2 exceeded the default page size, because cmsdev had not been updated to be aware of the CFS v3 pagination changes.
This PR overhauls the CFS API and CLI tests so that they have that awareness. It also adds in testing of CFS v3. Finally, it removes the checking of CFS component status, because that pretty much only resulted in people thinking CFS was having problems when it was just a product layer in a CFS session that failed to configure some node.
I tested these changes on fanta and mug, varying the page size value to make sure that the test handled the different scenarios.
=> CASMCMS-8958: cmsdev: Add CFS v3 coverage; make v2 testing aware of v3 pagination changes

CHANGELOG.md, cmsdev/internal/lib/common/cmd.go, cmsdev/internal/lib/k8s/k8s.go, cmsdev/internal/test/vcs/vcs_repo.go, cmsdev/redact_cmsdev_log.py, cray-cmstools-crayctldeploy.spec
There are a few ways in which cmsdev does a bad job with credentials:
1. It uses some of them by running commands whose arguments contain credentials, and whose arguments could be seen by running "ps -ef" on the system.
2. It includes some of them in the cmsdev log
This ticket takes care of both of those things.
=> CASMCMS-9029: cmsdev: More securely deal with credentials

CHANGELOG.md, barebones_image_test/api/api.py, barebones_image_test/bos/bos_template.py, barebones_image_test/test_resource.py
The barebones test creates a BOS session template, and it specifies empty strings in the boot set for the `rootfs_provider` and `rootfs_provider_passthrough` fields. These are not required fields for boot sets, but if they are specified, they cannot be empty strings. Previously this restriction was stated in the API spec text but not enforced. Starting in CSM 1.6, it is being enforced, and it caused the barebones test to fail.
This PR modifies the test so that it does not include these fields in the boot set of the session template it is creating.
It also improves the logging of the API calls being by the test (since I noticed the log file doesn't include most of these).
I tested this on fanta (where the problem was reported) and verified that it works.
=> CASMTRIAGE-7245: barebones test: Follow now-enforced API spec when creating BOS session template

CHANGELOG.md, cmsdev/internal/test/bos/bos.go
When BOS is upgraded, it creates a migration job, The first pod this job creates may fail if the BOS database is taking a while to get updated. In this case, the cmsdev test fails, because it currently fails when it sees any migration pod that is not successful. This PR changes it so that it does not fail when there are unsuccessful migration pods, provided there is also a successful one.
I have tested this on mug and verified that if there are no migration pods, or a failed pod and a successful one, then the test passes. I also verified that if there is only an unsuccessful migration pod, then the test fails.
=> CASMTRIAGE-7440: cmsdev: Do not fail BOS test for unsuccessful migration pods if there is also a successful one

CHANGELOG.md, cmsdev/internal/test/cfs/cfs_api.go, cmsdev/internal/test/ims/ims.go
Tested on mug and odin (where the problem was found)
=> CASMCMS-9188: cmsdev: Update CFS and IMS tests to explicitly check for 0-length resource ID fields

CHANGELOG.md, cmsdev/internal/cmd/test.go, cmsdev/internal/lib/common/common.go, cmsdev/internal/lib/common/printlog.go, cmsdev/internal/test/cfs/cfs.go, cmsdev/internal/test/ims/ims.go
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMCMS-9181: cmsdev Should record installed version of Cray CLI RPM
CASMCMS-9328: IMS: Store Artifact logs after signing key test failure
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
_List the environments in which these changes were tested._
it was …
=> CASMCMS-9181: Capture insatlled RPM versions during cmsdev test

CHANGELOG.md, cmsdev/go.mod
This is necessary in order to resolve some security vulnerabilities.
=> Build cmsdev using Golang 1.23

CHANGELOG.md, cmsdev/internal/lib/common/common.go, cmsdev/internal/test/ims/ims.go, cmsdev/internal/test/ims/ims_images_api.go, cmsdev/internal/test/ims/ims_public_key_api.go, cmsdev/internal/test/ims/ims_recipes_api.go, cmsdev/internal/test/ims/verify_ims_images.go, cmsdev/internal/test/ims/verify_ims_images_cli.go, cmsdev/internal/test/ims/verify_ims_public_key.go, cmsdev/internal/test/ims/verify_ims_public_key_cli.go, cmsdev/internal/test/ims/verify_ims_recipes.go, cmsdev/internal/test/ims/verify_ims_recipes_cli.go
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMCMS-9379: TESTS: IMS: cmsdev: Test v2 API and default version API
Tests are not performed for all supported versions and default API endpoints.
CASMCMS-9384: cmsdev should warn if docs-csm RPM is not installed
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL …
=> CASMCMS-9384, CASMCMS-9379: IMS cmsdev Test v2 API and default version API

CHANGELOG.md, cmsdev/internal/lib/common/common.go, cmsdev/internal/lib/common/helpers.go, cmsdev/internal/lib/k8s/k8s.go, cmsdev/internal/test/bos/bos_defs.go, cmsdev/internal/test/bos/bos_session.go, cmsdev/internal/test/bos/bos_session_tests.go, cmsdev/internal/test/bos/bos_sessions_api_tests.go, cmsdev/internal/test/bos/bos_sessiontemplate_api_tests.go, cmsdev/internal/test/bos/bos_sessiontemplate_tests.go, cmsdev/internal/test/bos/bos_sessiontemplates_api.go
CASMCMS-9348: BOS sessiontemplates, sessions CRUD API cmsdev tests
Tests added in cmsdev testsuite for BOS sessiontemplates and sessions.
- Sessiontemplates: It requires cfs configurations name, It also requires `boot_sets` related information which is dependent on 
images. The test is intended for BOS so using a dummy cfs configuration name since there is no validation for cfs configuration name if it exists or not.
* Test is designed to created session temapate for x86 and ARM architectures.
* Test suite includes create, update, delete, get by session tempate name and get all session templates.
* Other CRUD tests are skipped if create session template failes.
* Test suite is skipped if x86 and ARM images are not present in product catalog. test is marked as passed
and a warning is …
=> CASMCMS-9348: BOS sessiontemplates, sessions CRUD API cmsdev tests

CHANGELOG.md, cmsdev/internal/lib/test/cli.go, cmsdev/internal/test/bos/bos_cli.go, cmsdev/internal/test/bos/bos_session_tests.go, cmsdev/internal/test/bos/bos_sessions_api_tests.go, cmsdev/internal/test/bos/bos_sessions_cli.go, cmsdev/internal/test/bos/bos_sessions_cli_tests.go, cmsdev/internal/test/bos/bos_sessiontemplate_tests.go, cmsdev/internal/test/bos/bos_sessiontemplates_cli.go, cmsdev/internal/test/bos/bos_sessiontemplates_cli_tests.go, cmsdev/internal/test/ims/verify_ims_images_cli.go, cmsdev/internal/test/ims/verify_ims_public_key_cli.go, cmsdev/internal/test/ims/verify_ims_recipes_cli.go
[CASMCMS-9409](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9409): IMS cli test should suppress expected failures from log
CASMCMS-9348: BOS sessiontemplates and sessions CLI tests
Tests added in cmsdev testsuite for BOS sessiontemplates and sessions.
- Sessiontemplates: It requires cfs configurations name, It also requires `boot_sets` related information which is dependent on 
images. The test is intended for BOS so using a dummy cfs configuration name since there is no validation for cfs configuration name if it exists or not.
* Test is run for `default` and version `v2`
* Test is designed to created session temapate for x86 and ARM architectures.
* Test suite includes create, update, delete, get by session tempate name and get all session templates.
* Other CRUD tests are skipped if …
=> CASMCMS-9409,CASMCMS-9348: BOS sessiontemplates and sessions CLI tests

CHANGELOG.md, cmsdev/internal/lib/common/common.go, cmsdev/internal/test/cfs/cfs.go, cmsdev/internal/test/cfs/cfs_api.go, cmsdev/internal/test/cfs/cfs_configurations_api.go, cmsdev/internal/test/cfs/cfs_defs.go, cmsdev/internal/test/cfs/cfs_sources_api.go, cmsdev/internal/test/cfs/verify_cfs_configurations.go, cmsdev/internal/test/cfs/verify_cfs_sources.go
CASMCMS-9349:CFS configurations and sources CRUD API cmsdev tests
Tests added in cmsdev testsuite for CFS configurations and sources.
`configurations`
- Tests for both V2 and V3
- Following validations are performed after configurations creation.
- Verify the data of configurations with data supplied in the creation payload.
- Get configurations by name.
- Get all configuration and verify the newly created configuration is in the list.
`sources`
- Tests for supported API version V3
- Following validations are performed after source creation.
- Verify the data of sources with data supplied in the creation payload.
- Get sources by name.
- Get all sources and verify the newly created source is in the list.
Testing was performed on mug and test log is attached for reference. …
=> CASMCMS-9349:CFS configurations and sources CRUD API cmsdev tests

CHANGELOG.md, cmsdev/internal/test/ims/signingkeys.go
The script for the kiwi-ng recipe build no longer has hard-coded signing key names in the argument list to the kiwi-ng call. It now copies DST keys from the K8S secret, then compiles a list of all signing keys, and adds them dynamically to the command line for the call.
This broke the test, as the old test was checking that the signing keys baked into the kiwi-ng image were included in the command line. As this is now dynamically compiled, that logic no longer makes sense. I removed the bit checking the command line arguments, but retained the bit about checking that there are signing keys embedded into the image. I think that is the best we can do from a test stability standpoint.
* Resolves [CASMCMS-9465](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9465)
* `Mug`
I copied the new rpm …
=> CASMCMS-9465 - update ims signing key test.

CHANGELOG.md, cmsdev/internal/test/bos/bos_sessiontemplates_api.go
The `cmsdev` test currently creates BOS session templates with subtly incorrect kernel parameters strings in their boot sets. I noticed this on `fanta`:
```toml
kernel_parameters = "console=ttyS0,115200 bad_page=panic crashkernel=512M hugepagelist=2m-2g intel_iommu=off intel_pstate=disable iommu.passthrough=on modprobe.blacklist=amdgpu numa_interleave_omit=headless oops=panic pageblock_order=14 rd.neednet=1 rd.retry=10 rd.shell split_lock_detect=off systemd.unified_cgroup_hierarchy=1 ip=dhcp quiet spire_join_token=${SPIRE_JOIN_TOKEN} root=live:s3://boot-images/compute-csm-1.7-7.1.37-x86_64/rootfs nmd_data=url=s3://boot-images/compute-csm-1.7-7.1.37-x86_64/rootfs,etag=dc3790a50f95fa96c295829eb6aa7d0d"
```
In the two S3 paths, it is using the IMS image *name* where it should be using the …
=> CASMCMS-9534: cmsdev: Create BOS session templates with accurate kernel parameters

CHANGELOG.md, cmsdev/internal/test/bos/bos_sessiontemplates_api.go
This changes a misleading error message in the BOS test into a debug message.
I cherry-picked the fix for this from @kumarrahul04 's PR for CASMCMS-9540, since this fix is not related to it.
His change made this into a warning, but upon reflection, I don't think we would want a customer to run the test and see this warning message either (since it is not an unexpected thing to happen and does not indicate a problem). So I changed it to be a debug statement instead. And I reworded it to remove the word "error" from the text, just to make sure nobody panics if they saw that in the log file.
* Resolves [CASMCMS-9537](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9537)
* Caused by [CASMCMS-9472](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9472)
Ran the old test on fanta, verified that …
=> CASMCMS-9537: cmsdev: Remove misleading error message from BOS test
